/**
 * Koora Live — Pro Edition
 * Vanilla JS, no build tools, no direct API calls from the browser.
 * All data is read from static JSON files generated by
 * scripts/fetch-data.mjs and served through jsDelivr's free CDN,
 * so the site scales to any number of visitors with zero rate limits.
 */

// ---- CONFIG: fill these in once you push this repo to your own GitHub ----
const GITHUB_USER = "bankacem";
const GITHUB_REPO = "koora-live-scores";
const DATA_BRANCH = "data"; // the dedicated branch the workflow pushes JSON to
// ---------------------------------------------------------------------------

const CDN_BASE = `https://cdn.jsdelivr.net/gh/${GITHUB_USER}/${GITHUB_REPO}@${DATA_BRANCH}/data`;

const SUPPORTED_LANGS = ["en", "ar", "fr", "es"];
const RTL_LANGS = new Set(["ar"]);

class I18n {
  constructor() {
    this.dict = {};
    this.lang = localStorage.getItem("koora_lang") || (navigator.language?.startsWith("ar") ? "ar" : "en");
  }

  async load(lang) {
    if (!SUPPORTED_LANGS.includes(lang)) lang = "en";
    if (!this.dict[lang]) {
      const res = await fetch(`i18n/${lang}.json`);
      this.dict[lang] = await res.json();
    }
    this.lang = lang;
    localStorage.setItem("koora_lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL_LANGS.has(lang) ? "rtl" : "ltr";
  }

  t(key) {
    const parts = key.split(".");
    let val = this.dict[this.lang];
    for (const p of parts) val = val?.[p];
    return val ?? key;
  }

  applyToDom() {
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const badge = el.querySelector(".pulse");
      el.textContent = this.t(key);
      if (badge) el.appendChild(badge);
    });
  }
}

class DataService {
  async getLeagueScores(leagueId) {
    return this._safeFetch(`${CDN_BASE}/${leagueId}/scores.json`, { updatedAt: null, matches: [] });
  }

  async getLeagueStandings(leagueId) {
    return this._safeFetch(`${CDN_BASE}/${leagueId}/standings.json`, { updatedAt: null, standings: [] });
  }

  async getAllToday() {
    return this._safeFetch(`${CDN_BASE}/all-today.json`, { updatedAt: null, matches: [] });
  }

  async _safeFetch(url, fallback) {
    try {
      // cache-bust lightly so the CDN's edge refresh (purged by the workflow)
      // is picked up quickly without hammering origin
      const res = await fetch(`${url}?t=${Math.floor(Date.now() / 30000)}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (err) {
      console.warn("Data fetch failed for", url, err.message);
      return fallback;
    }
  }
}

class KooraApp {
  constructor() {
    this.i18n = new I18n();
    this.data = new DataService();
    this.currentLeague = new URLSearchParams(location.search).get("league") || "all";
    this.showLiveOnly = false;
    this.matches = [];
    this.standings = [];

    this.leagueNav = document.getElementById("league-nav");
    this.matchContainer = document.getElementById("match-container");
    this.loader = document.getElementById("loading-state");
    this.standingsWrap = document.getElementById("standings-wrap");
    this.standingsContainer = document.getElementById("standings-container");
    this.updatedLabel = document.getElementById("updated-label");
  }

  async init() {
    await this.i18n.load(this.i18n.lang);
    this.i18n.applyToDom();
    this.renderLeagueNav();
    this.bindEvents();
    await this.loadCurrentView();
    setInterval(() => this.loadCurrentView(), 20000); // client polls the CDN, not the origin API
  }

  bindEvents() {
    document.getElementById("btn-all")?.addEventListener("click", (e) => {
      this.showLiveOnly = false;
      this.toggleActiveBtn(e.target);
      this.render();
    });
    document.getElementById("btn-live")?.addEventListener("click", (e) => {
      this.showLiveOnly = true;
      this.toggleActiveBtn(e.target);
      this.render();
    });
    document.querySelectorAll(".lang-btn").forEach((btn) => {
      btn.addEventListener("click", async () => {
        await this.i18n.load(btn.dataset.lang);
        this.i18n.applyToDom();
        this.renderLeagueNav();
        this.render();
      });
    });
  }

  toggleActiveBtn(target) {
    document.querySelectorAll(".controls .btn").forEach((b) => b.classList.remove("active"));
    target.classList.add("active");
  }

  renderLeagueNav() {
    if (!this.leagueNav) return;
    const items = [{ id: "all", flag: "🌐", label: this.i18n.t("allLeagues") }].concat(
      LEAGUES.map((l) => ({ id: l.id, flag: l.flag, label: this.i18n.t(`leagues.${l.id}`) }))
    );
    this.leagueNav.innerHTML = items
      .map(
        (l) => `<button class="league-pill ${l.id === this.currentLeague ? "active" : ""}" data-league="${l.id}">
                  <span class="flag">${l.flag}</span>${l.label}
                </button>`
      )
      .join("");

    this.leagueNav.querySelectorAll(".league-pill").forEach((btn) => {
      btn.addEventListener("click", async () => {
        this.currentLeague = btn.dataset.league;
        const url = new URL(location.href);
        this.currentLeague === "all" ? url.searchParams.delete("league") : url.searchParams.set("league", this.currentLeague);
        history.replaceState({}, "", url);
        this.leagueNav.querySelectorAll(".league-pill").forEach((b) => b.classList.remove("active"));
        btn.classList.add("active");
        await this.loadCurrentView();
      });
    });
  }

  async loadCurrentView() {
    if (this.loader) this.loader.style.display = "block";

    if (this.currentLeague === "all") {
      const payload = await this.data.getAllToday();
      this.matches = payload.matches || [];
      this.lastUpdate = payload.updatedAt;
      this.standings = [];
      if (this.standingsWrap) this.standingsWrap.style.display = "none";
    } else {
      const leagueMeta = LEAGUES.find((l) => l.id === this.currentLeague);
      const scores = await this.data.getLeagueScores(this.currentLeague);
      this.matches = (scores.matches || []).map((m) => ({ ...m, league: this.currentLeague }));
      this.lastUpdate = scores.updatedAt;

      if (leagueMeta?.hasStandings && this.standingsWrap) {
        this.standingsWrap.style.display = "block";
        const st = await this.data.getLeagueStandings(this.currentLeague);
        this.standings = st.standings || [];
      } else if (this.standingsWrap) {
        this.standingsWrap.style.display = "none";
      }
    }

    if (this.loader) this.loader.style.display = "none";
    this.render();
  }

  render() {
    this.renderMatches();
    this.renderStandings();
    this.renderUpdatedLabel();
  }

  renderUpdatedLabel() {
    if (!this.updatedLabel || !this.lastUpdate) return;
    const secs = Math.max(0, Math.round((Date.now() - new Date(this.lastUpdate).getTime()) / 1000));
    const text = secs < 60 ? `${secs} ${this.i18n.t("secondsAgo")}` : `${Math.round(secs / 60)} ${this.i18n.t("minutesAgo")}`;
    this.updatedLabel.textContent = `${this.i18n.t("lastUpdated")}: ${text}`;
  }

  renderMatches() {
    if (!this.matchContainer) return;
    const list = this.showLiveOnly ? this.matches.filter((m) => m.isLive) : this.matches;

    if (list.length === 0) {
      this.matchContainer.innerHTML = `<p class="empty-state">${this.i18n.t("noMatches")}</p>`;
      return;
    }

    this.matchContainer.innerHTML = list
      .map((m) => {
        const statusDisplay = m.isLive ? `LIVE • ${m.status ?? ""}` : m.status ?? "";
        const leagueBadge = m.league ? `<span class="league-badge">${this.i18n.t(`leagues.${m.league}`)}</span>` : "";
        return `
        <article class="match-card ${m.isLive ? "is-live" : ""}" itemscope itemtype="http://schema.org/SportsEvent">
          <meta itemprop="name" content="${m.name ?? ""}">
          <meta itemprop="startDate" content="${m.date ?? ""}">
          ${leagueBadge}
          <div class="team home">
            <span>${m.home?.name ?? ""}</span>
            ${m.home?.logo ? `<img src="${m.home.logo}" alt="" class="team-logo" loading="lazy">` : ""}
          </div>
          <div class="score-box">
            <span class="score">${m.home?.score ?? "-"} : ${m.away?.score ?? "-"}</span>
            <span class="status ${m.isLive ? "live" : ""}">${statusDisplay}</span>
          </div>
          <div class="team away">
            ${m.away?.logo ? `<img src="${m.away.logo}" alt="" class="team-logo" loading="lazy">` : ""}
            <span>${m.away?.name ?? ""}</span>
          </div>
        </article>`;
      })
      .join("");
  }

  renderStandings() {
    if (!this.standingsContainer) return;
    if (!this.standings.length) {
      this.standingsContainer.innerHTML = `<p class="empty-state">${this.i18n.t("noStandings")}</p>`;
      return;
    }
    const t = (k) => this.i18n.t(k);
    const rows = this.standings
      .map(
        (team) => `
      <tr>
        <td class="text-center rank">${team.rank}</td>
        <td class="team-cell">
          ${team.logo ? `<img src="${team.logo}" alt="" class="table-logo" loading="lazy">` : ""}
          <span>${team.team}</span>
        </td>
        <td class="text-center">${team.played}</td>
        <td class="text-center">${team.wins}</td>
        <td class="text-center">${team.draws}</td>
        <td class="text-center">${team.losses}</td>
        <td class="text-center">${team.goalDiff > 0 ? "+" + team.goalDiff : team.goalDiff}</td>
        <td class="text-center points">${team.points}</td>
      </tr>`
      )
      .join("");

    this.standingsContainer.innerHTML = `
      <table class="table-responsive">
        <thead>
          <tr>
            <th class="text-center">${t("tableRank")}</th>
            <th>${t("tableTeam")}</th>
            <th class="text-center">${t("tablePlayed")}</th>
            <th class="text-center">${t("tableWins")}</th>
            <th class="text-center">${t("tableDraws")}</th>
            <th class="text-center">${t("tableLosses")}</th>
            <th class="text-center">${t("tableGD")}</th>
            <th class="text-center">${t("tablePoints")}</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>`;
  }
}

document.addEventListener("DOMContentLoaded", () => {
  new KooraApp().init();
});
