/**
 * Koora Live — Pro Edition
 * Vanilla JS, no build tools, no direct API calls from the browser.
 * All data is read from static JSON files generated by
 * scripts/fetch-data.mjs and served through jsDelivr's free CDN,
 * so the site scales to any number of visitors with zero rate limits.
 */

// ---- CONFIG: fill these in once you push this repo to your own GitHub ----
const GITHUB_USER = "bankacem";
const GITHUB_REPO = "koora-live-scores";
const DATA_BRANCH = "data"; // the dedicated branch the workflow pushes JSON to
// ---------------------------------------------------------------------------

const CDN_BASE = `https://cdn.jsdelivr.net/gh/${GITHUB_USER}/${GITHUB_REPO}@${DATA_BRANCH}/data`;

const SUPPORTED_LANGS = ["en", "ar", "fr", "es"];
const RTL_LANGS = new Set(["ar"]);

class I18n {
  constructor() {
    this.dict = {};
    this.lang = localStorage.getItem("koora_lang") || (navigator.language?.startsWith("ar") ? "ar" : "en");
  }

  async load(lang) {
    if (!SUPPORTED_LANGS.includes(lang)) lang = "en";
    if (!this.dict[lang]) {
      const res = await fetch(`i18n/${lang}.json`);
      this.dict[lang] = await res.json();
    }
    this.lang = lang;
    localStorage.setItem("koora_lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL_LANGS.has(lang) ? "rtl" : "ltr";
  }

  t(key) {
    const parts = key.split(".");
    let val = this.dict[this.lang];
    for (const p of parts) val = val?.[p];
    return val ?? key;
  }

  applyToDom() {
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const badge = el.querySelector(".pulse");
      el.textContent = this.t(key);
      if (badge) el.appendChild(badge);
    });
  }
}

class DataService {
  async getLeagueScores(leagueId) {
    return this._safeFetch(`${CDN_BASE}/${leagueId}/scores.json`, { updatedAt: null, matches: [] });
  }

  async getLeagueStandings(leagueId) {
    return this._safeFetch(`${CDN_BASE}/${leagueId}/standings.json`, { updatedAt: null, standings: [] });
  }

  async getAllToday() {
    return this._safeFetch(`${CDN_BASE}/all-today.json`, { updatedAt: null, matches: [] });
  }

  async _safeFetch(url, fallback) {
    try {
      // cache-bust lightly so the CDN's edge refresh (purged by the workflow)
      // is picked up quickly without hammering origin
      const res = await fetch(`${url}?t=${Math.floor(Date.now() / 30000)}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (err) {
      console.warn("Data fetch failed for", url, err.message);
      return fallback;
    }
  }
}

class KooraApp {
  constructor() {
    this.i18n = new I18n();
    this.data = new DataService();
    this.currentLeague = new URLSearchParams(location.search).get("league") || "all";
    this.showLiveOnly = false;
    this.matches = [];
    this.standings = [];

    this.leagueNav = document.getElementById("league-nav");
    this.matchContainer = document.getElementById("match-container");
    this.loader = document.getElementById("loading-state");
    this.standingsWrap = document.getElementById("standings-wrap");
    this.standingsContainer = document.getElementById("standings-container");
    this.updatedLabel = document.getElementById("updated-label");
    this.articlesContainer = document.getElementById("articles-container");
    this.modal = document.getElementById("article-modal");
    this.modalClose = document.getElementById("modal-close-btn");
    this.modalBody = document.getElementById("modal-article-body");
  }

  async init() {
    await this.i18n.load(this.i18n.lang);
    this.i18n.applyToDom();
    this.renderLeagueNav();
    this.bindEvents();
    this.renderArticles();
    await this.loadCurrentView();
    setInterval(() => this.loadCurrentView(), 20000); // client polls the CDN, not the origin API
  }

  bindEvents() {
    document.getElementById("btn-all")?.addEventListener("click", (e) => {
      this.showLiveOnly = false;
      this.toggleActiveBtn(e.target);
      this.render();
    });
    document.getElementById("btn-live")?.addEventListener("click", (e) => {
      this.showLiveOnly = true;
      this.toggleActiveBtn(e.target);
      this.render();
    });
    document.querySelectorAll(".lang-btn").forEach((btn) => {
      btn.addEventListener("click", async () => {
        await this.i18n.load(btn.dataset.lang);
        this.i18n.applyToDom();
        this.renderLeagueNav();
        this.render();
        this.renderArticles();
      });
    });

    if (this.modalClose) {
      this.modalClose.addEventListener("click", () => this.closeArticleModal());
    }
    if (this.modal) {
      this.modal.addEventListener("click", (e) => {
        if (e.target === this.modal) this.closeArticleModal();
      });
    }
  }

  toggleActiveBtn(target) {
    document.querySelectorAll(".controls .btn").forEach((b) => b.classList.remove("active"));
    target.classList.add("active");
  }

  renderLeagueNav() {
    if (!this.leagueNav) return;
    const items = [{ id: "all", flag: "🌐", label: this.i18n.t("allLeagues") }].concat(
      LEAGUES.map((l) => ({ id: l.id, flag: l.flag, label: this.i18n.t(`leagues.${l.id}`) }))
    );
    this.leagueNav.innerHTML = items
      .map(
        (l) => `<button class="league-pill ${l.id === this.currentLeague ? "active" : ""}" data-league="${l.id}">
                  <span class="flag">${l.flag}</span>${l.label}
                </button>`
      )
      .join("");

    this.leagueNav.querySelectorAll(".league-pill").forEach((btn) => {
      btn.addEventListener("click", async () => {
        this.currentLeague = btn.dataset.league;
        const url = new URL(location.href);
        this.currentLeague === "all" ? url.searchParams.delete("league") : url.searchParams.set("league", this.currentLeague);
        history.replaceState({}, "", url);
        this.leagueNav.querySelectorAll(".league-pill").forEach((b) => b.classList.remove("active"));
        btn.classList.add("active");
        await this.loadCurrentView();
      });
    });
  }

  async loadCurrentView() {
    if (this.loader) this.loader.style.display = "block";

    if (this.currentLeague === "all") {
      const payload = await this.data.getAllToday();
      this.matches = payload.matches || [];
      this.lastUpdate = payload.updatedAt;
      this.standings = [];
      if (this.standingsWrap) this.standingsWrap.style.display = "none";
    } else {
      const leagueMeta = LEAGUES.find((l) => l.id === this.currentLeague);
      const scores = await this.data.getLeagueScores(this.currentLeague);
      this.matches = (scores.matches || []).map((m) => ({ ...m, league: this.currentLeague }));
      this.lastUpdate = scores.updatedAt;

      if (leagueMeta?.hasStandings && this.standingsWrap) {
        this.standingsWrap.style.display = "block";
        const st = await this.data.getLeagueStandings(this.currentLeague);
        this.standings = st.standings || [];
      } else if (this.standingsWrap) {
        this.standingsWrap.style.display = "none";
      }
    }

    if (this.loader) this.loader.style.display = "none";
    this.render();
  }

  render() {
    this.renderMatches();
    this.renderStandings();
    this.renderUpdatedLabel();
  }

  renderUpdatedLabel() {
    if (!this.updatedLabel || !this.lastUpdate) return;
    const secs = Math.max(0, Math.round((Date.now() - new Date(this.lastUpdate).getTime()) / 1000));
    const text = secs < 60 ? `${secs} ${this.i18n.t("secondsAgo")}` : `${Math.round(secs / 60)} ${this.i18n.t("minutesAgo")}`;
    this.updatedLabel.textContent = `${this.i18n.t("lastUpdated")}: ${text}`;
  }

  renderMatches() {
    if (!this.matchContainer) return;
    const list = this.showLiveOnly ? this.matches.filter((m) => m.isLive) : this.matches;

    if (list.length === 0) {
      this.matchContainer.innerHTML = `<p class="empty-state">${this.i18n.t("noMatches")}</p>`;
      return;
    }

    this.matchContainer.innerHTML = list
      .map((m) => {
        const statusDisplay = m.isLive ? `LIVE • ${m.status ?? ""}` : m.status ?? "";
        const leagueBadge = m.league ? `<span class="league-badge">${this.i18n.t(`leagues.${m.league}`)}</span>` : "";
        return `
        <article class="match-card ${m.isLive ? "is-live" : ""}" itemscope itemtype="http://schema.org/SportsEvent">
          <meta itemprop="name" content="${m.name ?? ""}">
          <meta itemprop="startDate" content="${m.date ?? ""}">
          ${leagueBadge}
          <div class="team home">
            <span>${m.home?.name ?? ""}</span>
            ${m.home?.logo ? `<img src="${m.home.logo}" alt="" class="team-logo" loading="lazy">` : ""}
          </div>
          <div class="score-box">
            <span class="score">${m.home?.score ?? "-"} : ${m.away?.score ?? "-"}</span>
            <span class="status ${m.isLive ? "live" : ""}">${statusDisplay}</span>
          </div>
          <div class="team away">
            ${m.away?.logo ? `<img src="${m.away.logo}" alt="" class="team-logo" loading="lazy">` : ""}
            <span>${m.away?.name ?? ""}</span>
          </div>
        </article>`;
      })
      .join("");
  }

  renderStandings() {
    if (!this.standingsContainer) return;
    if (!this.standings.length) {
      this.standingsContainer.innerHTML = `<p class="empty-state">${this.i18n.t("noStandings")}</p>`;
      return;
    }
    const t = (k) => this.i18n.t(k);
    const rows = this.standings
      .map(
        (team) => `
      <tr>
        <td class="text-center rank">${team.rank}</td>
        <td class="team-cell">
          ${team.logo ? `<img src="${team.logo}" alt="" class="table-logo" loading="lazy">` : ""}
          <span>${team.team}</span>
        </td>
        <td class="text-center">${team.played}</td>
        <td class="text-center">${team.wins}</td>
        <td class="text-center">${team.draws}</td>
        <td class="text-center">${team.losses}</td>
        <td class="text-center">${team.goalDiff > 0 ? "+" + team.goalDiff : team.goalDiff}</td>
        <td class="text-center points">${team.points}</td>
      </tr>`
      )
      .join("");

    this.standingsContainer.innerHTML = `
      <table class="table-responsive">
        <thead>
          <tr>
            <th class="text-center">${t("tableRank")}</th>
            <th>${t("tableTeam")}</th>
            <th class="text-center">${t("tablePlayed")}</th>
            <th class="text-center">${t("tableWins")}</th>
            <th class="text-center">${t("tableDraws")}</th>
            <th class="text-center">${t("tableLosses")}</th>
            <th class="text-center">${t("tableGD")}</th>
            <th class="text-center">${t("tablePoints")}</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>`;
  }
  // ---- News / Articles ----
  // Static editorial content for now (kept out of the auto-updating data
  // pipeline on purpose). Add languages by adding a key here matching
  // SUPPORTED_LANGS; unsupported languages fall back to English.
  getArticlesData() {
    const en = [
      {
        id: "art-1",
        title: "Premier League Title Race Heats Up: Tactics and Predictions",
        excerpt: "An intense battle for the Premier League crown erupts between Arsenal, Manchester City, and Liverpool.",
        tag: "Premier League",
        date: "July 28, 2026",
        image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=400",
        author: "Koora Live Staff",
        content:
          "The English Premier League title race is reaching an unprecedented level of drama this season. Arsenal's defensive stability, paired with Manchester City's tactical versatility and Liverpool's high-octane offensive transitions, has created a three-way tug of war.\n\nWith only a few rounds remaining, squad depth and high-pressure performance will determine who raises the historic silverware.",
      },
      {
        id: "art-2",
        title: "The Evolution of Modern Football Formations and Strategies",
        excerpt: "Modern football demands hybrid positions and fluid shape transitions.",
        tag: "Tactics",
        date: "July 27, 2026",
        image: "https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=400",
        author: "Tactical Analyst",
        content:
          "Gone are the days of rigid 4-4-2 systems. Today's elite football is defined by continuous fluid rotation and hybrid player roles: inverted fullbacks, high pressing triggers, and sweeper keepers integrated into build-up play.",
      },
      {
        id: "art-3",
        title: "Summer Transfer Window: Hits, Misses and Surprise Signings",
        excerpt: "A complete review of the biggest summer transfers and their immediate impact.",
        tag: "Transfers",
        date: "July 26, 2026",
        image: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&q=80&w=400",
        author: "Newsroom",
        content:
          "The summer transfer window has closed, leaving behind dramatic deals, astronomical valuations, and tactical restructuring across the continent's biggest clubs.",
      },
    ];

    const ar = [
      {
        id: "art-1",
        title: "تحليل صراع صدارة الدوري الإنجليزي الممتاز والمنافسة الشرسة",
        excerpt: "يشتعل الصراع على الصدارة بين آرسنال ومانشستر سيتي وليفربول هذا الموسم.",
        tag: "الدوري الإنجليزي",
        date: "28 يوليو 2026",
        image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=400",
        author: "كورة لايف",
        content:
          "تشهد بطولة الدوري الإنجليزي الممتاز صراعاً ملحمياً هذا الموسم على الصدارة. آرسنال بصلابته الدفاعية، مانشستر سيتي بمرونته التكتيكية، وليفربول بقوته الهجومية يتنافسون جميعاً على اللقب.\n\nمع بقاء جولات قليلة، سيكون عمق التشكيلة هو العامل الحاسم.",
      },
      {
        id: "art-2",
        title: "تكتيكات المدربين الجدد وتأثيرها على شكل الأداء في الملاعب",
        excerpt: "تغييرات جذرية يشهدها تكتيك اللعب هذا العام في الكرة الأوروبية.",
        tag: "تحليل كروي",
        date: "27 يوليو 2026",
        image: "https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=400",
        author: "محلل كورة لايف",
        content:
          "لقد ولت أيام الخطط الجامدة مثل 4-4-2. كرة القدم الحديثة أصبحت أكثر مرونة تعتمد على المراكز الهجينة، الظهير الوهمي، ومحفزات الضغط العالي.",
      },
      {
        id: "art-3",
        title: "أفضل صفقات الصيف وتوقعات الخبراء للموسم الكروي الجديد",
        excerpt: "تقرير شامل عن أهم الانتقالات الكروية وتأثيرها المتوقع.",
        tag: "انتقالات",
        date: "26 يوليو 2026",
        image: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&q=80&w=400",
        author: "غرفة الأخبار",
        content:
          "أغلقت نافذة الانتقالات الصيفية أبوابها، مخلفة وراءها صفقات مثيرة وأرقاماً فلكية وإعادة هيكلة واضحة لخطط الأندية الكبرى.",
      },
    ];

    return { en, ar, fr: en, es: en }[this.i18n.lang] || en;
  }

  renderArticles() {
    if (!this.articlesContainer) return;
    const articles = this.getArticlesData();
    const readMore = { en: "Read More →", ar: "اقرأ المزيد ←", fr: "Lire la suite →", es: "Leer más →" }[this.i18n.lang] || "Read More →";

    this.articlesContainer.innerHTML = articles
      .map(
        (art) => `
      <article class="article-card" data-id="${art.id}">
        <img src="${art.image}" alt="${art.title}" class="article-image" loading="lazy">
        <div class="article-content">
          <span class="article-tag">${art.tag}</span>
          <h3 class="article-title">${art.title}</h3>
          <p class="article-excerpt">${art.excerpt}</p>
          <div style="font-weight:700; color: var(--primary); font-size:0.85rem;">${readMore}</div>
          <div class="article-meta"><span>${art.author}</span><span>${art.date}</span></div>
        </div>
      </article>`
      )
      .join("");

    this.articlesContainer.querySelectorAll(".article-card").forEach((card) => {
      card.addEventListener("click", () => this.openArticleModal(card.getAttribute("data-id"), articles));
    });
  }

  openArticleModal(articleId, articles) {
    if (!this.modal || !this.modalBody) return;
    const article = articles.find((a) => a.id === articleId);
    if (!article) return;

    this.modalBody.innerHTML = `
      <span class="modal-tag">${article.tag}</span>
      <h2 class="modal-title">${article.title}</h2>
      <div class="modal-meta"><strong>${article.author}</strong> · ${article.date}</div>
      <img src="${article.image}" alt="${article.title}" class="modal-img">
      <div class="modal-desc">${article.content}</div>`;

    this.modal.classList.add("show");
    document.body.style.overflow = "hidden";
  }

  closeArticleModal() {
    if (!this.modal) return;
    this.modal.classList.remove("show");
    document.body.style.overflow = "auto";
  }
}

document.addEventListener("DOMContentLoaded", () => {
  new KooraApp().init();
});
